(define (problem pb2)
   (:domain blocksworld)
   (:objects vanilla strawberry nuts cup1 cup2)
   (:init
     (is-cup cup1)
     (is-cup cup2)
     (clear cup1)
     (clear cup2)
     (is-vanilla vanilla)
     (is-straw strawberry)
     (is-nuts nuts)
   )
   (:goal ( and 
   				(Order cup1 vanilla nuts vanilla) 
   				(Order cup2 vanilla strawberry nuts) 
   		  )
   )
)