(define (domain sorbet-station)
  (:requirements :strips :equality)
  (:predicates
    (Stackable ?o ?r)
    (Tub ?r)
    (Bowl ?r)
    (Scoop ?r)

    (Gripped ?o)
    (Grasp ?o ?g)
    (Kin ?o ?p ?g ?q ?t)
    (FreeMotion ?q1 ?t ?q2)
    (HoldingMotion ?q1 ?t ?q2 ?o ?g)
    (Supported ?o ?p ?r)
    (TrajCollision ?t ?o2 ?p2)

    (AtPose ?o ?p)
    (AtGrasp ?o ?g)
    (HandEmpty)
    (AtConf ?q)
    (CanMove)
    (Cleaned)
    (Wash ?o)

    (First ?o ?r)
    (Second ?o ?r)
    (isEmpty)
    (isOne)
    (isTwo)
    (One ?o)
    (Two ?o)
    (Holding ?o)
    (UnsafeTraj ?t)
  )

  (:action move_free
    :parameters (?q1 ?q2 ?t)
    :precondition (and (FreeMotion ?q1 ?t ?q2)
                       (AtConf ?q1) (HandEmpty) (CanMove) (not (UnsafeTraj ?t)))
    :effect (and (AtConf ?q2)
                 (not (AtConf ?q1)) (not (CanMove)))
  )
  (:action move_holding
    :parameters (?q1 ?q2 ?o ?g ?t)
    :precondition (and (FreeMotion ?q1 ?t ?q2)
                       (AtConf ?q1) (AtGrasp ?o ?g) (CanMove) (Cleaned) (not (UnsafeTraj ?t)))
    :effect (and (AtConf ?q2)
                 (not (AtConf ?q1)) (not (CanMove)))
  )
  (:action scoop
    :parameters (?o ?p ?g ?q ?t)
    :precondition (and (Kin ?o ?p ?g ?q ?t)
                       (AtPose ?o ?p) (HandEmpty) (AtConf ?q) (Cleaned) (not (UnsafeTraj ?t)) (Cleaned))
    :effect (and (AtGrasp ?o ?g) (CanMove)
                 (not (AtPose ?o ?p)) (not (HandEmpty)))
  )
  (:action dump_first
    :parameters (?o ?p ?g ?q ?t)
    :precondition (and (Kin ?o ?p ?g ?q ?t)
                       (AtGrasp ?o ?g) (AtConf ?q) (isEmpty) (Cleaned) (not (UnsafeTraj ?t)))
    :effect (and (AtPose ?o ?p) (HandEmpty) (CanMove)
                 (not (AtGrasp ?o ?g))
                 (not (Cleaned)) (not(isEmpty)) (One ?o))
  )
  (:action dump_second
    :parameters (?o ?p ?g ?q ?t)
    :precondition (and (Kin ?o ?p ?g ?q ?t)
                       (AtGrasp ?o ?g) (AtConf ?q) (Cleaned) (not(isEmpty)) (not (UnsafeTraj ?t)))
    :effect (and (AtPose ?o ?p) (HandEmpty) (CanMove)
                 (not (AtGrasp ?o ?g))
                 (not (Cleaned)) (Two ?o))
  )
  (:action wash
    :parameters (?o ?p ?g ?q ?t)
    :precondition (and (Kin ?o ?p ?g ?q ?t)
                       (AtPose ?o ?p) (HandEmpty) (Wash ?o) (AtConf ?q) (not (UnsafeTraj ?t)) (not (Cleaned)))
    :effect (and (CanMove) (Cleaned)
                 (not (AtPose ?o ?p)))
  )
 
  (:derived (First ?o ?r)
    (exists (?p) (and (One ?o) (Supported ?o ?p ?r)
                      (AtPose ?o ?p) (Bowl ?r)))
  )
  (:derived (Second ?o ?r)
    (exists (?p) (and (Two ?o) (Supported ?o ?p ?r)
                      (AtPose ?o ?p) (Scoop ?r) (Scoop ?o)))
  )


  (:derived (Holding ?o)
    (exists (?g) (and (Grasp ?o ?g)
                      (AtGrasp ?o ?g)))
  )
  ; (:derived (UnsafeTraj ?t)
  ;  (exists (?o2 ?p2) (and (TrajCollision ?t ?o2 ?p2)
  ;                         (AtPose ?o2 ?p2)))
  ; )
)